// Generated by CoffeeScript 1.3.3
(function() {
  var TwitterLib, credentials;

  TwitterLib = require('twit');

  credentials = require('./credentials');

  exports.twitter = new TwitterLib({
    consumer_key: credentials.twitter.consumer_key,
    consumer_secret: credentials.twitter.consumer_secret,
    access_token: credentials.twitter.access_token_key,
    access_token_secret: credentials.twitter.access_token_secret
  });

  exports.pullList = function(callback) {
    return exports.twitter.get('lists/members', {
      'slug': 'football-players',
      'owner_screen_name': 'dailyemerald',
      'cursor': '-1'
    }, function(err, reply) {
      var listIDs, user, _i, _len, _ref;
      if (err === null) {
        listIDs = [];
        _ref = reply.users;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          user = _ref[_i];
          listIDs.push(user.id);
        }
        return callback(listIDs);
      } else {
        return callback([]);
      }
    });
  };

  exports.startStream = function(followIDs, newTweetCallback) {
    var stream;
    stream = exports.twitter.stream('statuses/filter', {
      track: ["goducks", "dailyemerald"],
      follow: followIDs,
      locations: [44.053591, -123.077431, 44.061663, -123.059353]
    });
    return stream.on('tweet', function(data) {
      return newTweetCallback(data);
    });
  };

}).call(this);
